### ISSUE TITLE
JIRA 7 incompatibility

### ISSUE THREAD

**Issue by Daerados** [chauth/jira_http_authenticator#4]
Greetings.

There's an issue with shibboleth, that it calling for deprecated methods. In this particular case:

http://prntscr.com/9gs5wr

Could update be expected any time soon?

**Comment by jlinnosa** [comment]
You can try if my patch works: https://github.com/jlinnosa/jira_http_authenticator

**Comment by kevinfoote** [comment]
I need to get a JIRA 7 install local. Working on it :)

**Comment by kevinfoote** [comment]
jlinnosa can you please create a pull request for your jira 7 changes?
also please explain this next commit 

https://github.com/jlinnosa/jira_http_authenticator/commit/17916fc6805124877d0617be4499f46f3a08292a

**Comment by jlinnosa** [comment]
I isolated the one commit and made a pull request, I think. The other commit was just IntelliJ wanting to optimize imports and I couldn't contain myself.

**Comment by kevinfoote** [comment]
pulled in jlinnosa request.
had to add repos for build to happen (will revisit these depends)

**Comment by jlinnosa** [comment]
I'd suggest using the Atlassian Plugin SDK; it has all the required repos configured.

```
$ atlas-version 

ATLAS Version:    6.2.2
ATLAS Home:       /usr/share/atlassian-plugin-sdk-6.2.2
ATLAS Scripts:    /usr/share/atlassian-plugin-sdk-6.2.2/bin
ATLAS Maven Home: /usr/share/atlassian-plugin-sdk-6.2.2/apache-maven-3.2.1
AMPS Version:     6.2.1
```

I just cloned master into a tmp dir and `atlas-package` compiled and packaged the plugin without any problem.

**Comment by kevinfoote** [comment]
yea will do thanks!
